# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems:
  - jekyll-assets

assets:
  compress:
    css: true
    js: true

  #

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #

  assets:
    - "*.png"
    - "bundle.css"

  #

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

  #

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true

title: آموزش شبکه های کامپیوتری
email: i@a69.ir
description: > # this means to ignore newlines until "baseurl:"
  این یک آموزش برای آنهایی است که برای اولین بار با مفاهیم شبکه برخورد می کنند.
  در این آموزش سعی خواهیم کرد مفاهیم را به ساده ترین نحوه ممکن مطرح نماییم.
  در این آموزش سعی خواهد شد تا حد ممکن فارغ از هرنوع نرم افزار و سیستم عامل به بررسی کارکرد و رفتار شبکه های کامپیوتری اشاره کنیم.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://netwokmore.ir" # the base hostname & protocol for your site
twitter_username: aminfar69
github_username:  a69

# Build settings
markdown: kramdown
